name = "noto-sans-mono"
version = "2.014"
description = "Monospaced sans-serif typeface for Latin, Greek, and Cyrillic text"
homepage = "https://fonts.google.com/noto/use"
repository = "https://github.com/notofonts/latin-greek-cyrillic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSansMono-v2.014/NotoSansMono-v2.014.zip"
hash = "sha256:090cf6c5e03f337a755630ca888b1fef463e64ae7b33ee134e9309c05f978732"

[sources.contents]
type = "archive"
fonts = [
  "NotoSansMono/hinted/ttf/NotoSansMono-Black.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Bold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Condensed.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedBlack.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedExtraBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedExtraLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedMedium.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedSemiBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-CondensedThin.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensed.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedBlack.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedExtraBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedExtraLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedMedium.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedSemiBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraCondensedThin.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-ExtraLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Light.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Medium.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Regular.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensed.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedBlack.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedExtraBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedExtraLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedLight.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedMedium.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedSemiBold.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-SemiCondensedThin.ttf",
  "NotoSansMono/hinted/ttf/NotoSansMono-Thin.ttf",
]
ignore = [
  { glob = "NotoSansMono/googlefonts/ttf/*.ttf" },
  { glob = "NotoSansMono/googlefonts/variable/*.ttf" },
  { glob = "NotoSansMono/unhinted/otf/*.otf" },
  { glob = "NotoSansMono/unhinted/slim-variable-ttf/*.ttf" },
  { glob = "NotoSansMono/unhinted/ttf/*.ttf" },
  { glob = "NotoSansMono/unhinted/variable/*.ttf" },
]
