name = "udev-gothic-nf"
display-name = "UDEV Gothic NF"
version = "2.2.0"
description = "Japanese programming font combining BIZ UD Gothic and JetBrains Mono with Nerd Fonts"
aliases = [
  "UDEV Gothic NFLG",
  "UDEV Gothis 35NF",
  "UDEV Gothis 35NFLG",
]
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.2.0/UDEVGothic_NF_v2.2.0.zip"
hash = "sha256:45faeef7b5d8bc591bcc5887a2ca0c5fb9028066f18a5a52cd6f10b7d655ba37"
files = [
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNF-Regular.ttf", title = "UDEV Gothic NF Regular" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNF-Bold.ttf", title = "UDEV Gothic NF Bold" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNF-Italic.ttf", title = "UDEV Gothic NF Italic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNF-BoldItalic.ttf", title = "UDEV Gothic NF BoldItalic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNFLG-Regular.ttf", title = "UDEV Gothic NFLG Regular" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNFLG-Bold.ttf", title = "UDEV Gothic NFLG Bold" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNFLG-Italic.ttf", title = "UDEV Gothic NFLG Italic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothicNFLG-BoldItalic.ttf", title = "UDEV Gothic NFLG BoldItalic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NF-Regular.ttf", title = "UDEV Gothic 35NF Regular" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NF-Bold.ttf", title = "UDEV Gothic 35NF Bold" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NF-Italic.ttf", title = "UDEV Gothic 35NF Italic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NF-BoldItalic.ttf", title = "UDEV Gothic 35NF BoldItalic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NFLG-Regular.ttf", title = "UDEV Gothic 35NFLG Regular" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NFLG-Bold.ttf", title = "UDEV Gothic 35NFLG Bold" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NFLG-Italic.ttf", title = "UDEV Gothic 35NFLG Italic" },
  { path = "UDEVGothic_NF_v2.2.0/UDEVGothic35NFLG-BoldItalic.ttf", title = "UDEV Gothic 35NFLG BoldItalic" },
]
