name = "udev-gothic-hs"
display-name = "UDEV Gothic HS"
version = "2.2.0"
description = "Japanese programming font combining BIZ UD Gothic and JetBrains Mono with hidden full-width spaces"
aliases = [
  "UDEV Gothic HSJPDOC",
  "UDEV Gothic HSLG",
  "UDEV Gothis 35HS",
  "UDEV Gothis 35HSJPDOC",
  "UDEV Gothis 35HSLG",
]
faces = [
  "UDEV Gothic HS Regular",
  "UDEV Gothic HS Bold",
  "UDEV Gothic HS Italic",
  "UDEV Gothic HS BoldItalic",
  "UDEV Gothic HSJPDOC Regular",
  "UDEV Gothic HSJPDOC Bold",
  "UDEV Gothic HSJPDOC Italic",
  "UDEV Gothic HSJPDOC BoldItalic",
  "UDEV Gothic HSLG Regular",
  "UDEV Gothic HSLG Bold",
  "UDEV Gothic HSLG Italic",
  "UDEV Gothic HSLG BoldItalic",
  "UDEV Gothic 35HS Regular",
  "UDEV Gothic 35HS Bold",
  "UDEV Gothic 35HS Italic",
  "UDEV Gothic 35HS BoldItalic",
  "UDEV Gothic 35HSJPDOC Regular",
  "UDEV Gothic 35HSJPDOC Bold",
  "UDEV Gothic 35HSJPDOC Italic",
  "UDEV Gothic 35HSJPDOC BoldItalic",
  "UDEV Gothic 35HSLG Regular",
  "UDEV Gothic 35HSLG Bold",
  "UDEV Gothic 35HSLG Italic",
  "UDEV Gothic 35HSLG BoldItalic",
]
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.2.0/UDEVGothic_HS_v2.2.0.zip"
hash = "sha256:570d03cb98d15834a5f6e1323843dfdc9f79d4b0c4bace123bb12de0806d9545"
files = [
  "UDEVGothic_HS_v2.2.0/UDEVGothicHS-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHS-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHS-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHS-BoldItalic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSJPDOC-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSJPDOC-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSJPDOC-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSJPDOC-BoldItalic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSLG-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSLG-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSLG-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothicHSLG-BoldItalic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HS-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HS-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HS-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HS-BoldItalic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSJPDOC-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSJPDOC-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSJPDOC-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSJPDOC-BoldItalic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSLG-Regular.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSLG-Bold.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSLG-Italic.ttf",
  "UDEVGothic_HS_v2.2.0/UDEVGothic35HSLG-BoldItalic.ttf",
]
