name = "jetbrains-mono"
display-name = "JetBrains Mono"
version = "2.304"
description = "The free and open-source typeface for developers, by JetBrains"
aliases = []
homepage = "https://jetbrains.com/mono"
repository = "https://github.com/JetBrains/JetBrainsMono"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip"
hash = "sha256:6f6376c6ed2960ea8a963cd7387ec9d76e3f629125bc33d1fdcd7eb7012f7bbf"

[sources.contents]
type = "archive"
fonts = [
  "fonts/variable/JetBrainsMono[wght].ttf",
  "fonts/variable/JetBrainsMono-Italic[wght].ttf",
]
ignore = [
  { glob = "fonts/ttf/JetBrainsMono-*.ttf" },
  { glob = "fonts/ttf/JetBrainsMonoNL-*.ttf" },
]
