name = "udev-gothic-hs"
display-name = "UDEV Gothic HS"
version = "2.1.0"
description = "Japanese programming font combining BIZ UD Gothic and JetBrains Mono with hidden full-width spaces"
aliases = [
  "UDEV Gothic HSJPDOC",
  "UDEV Gothic HSLG",
  "UDEV Gothis 35HS",
  "UDEV Gothis 35HSJPDOC",
  "UDEV Gothis 35HSLG",
]
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.1.0/UDEVGothic_HS_v2.1.0.zip"
hash = "sha256:25e6730e929194b15d788aa9a67f0b8285214904a693c753ecbb020da54abe0f"

[sources.contents]
type = "archive"
fonts = [
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHS-Regular.ttf", title = "UDEV Gothic HS Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHS-Bold.ttf", title = "UDEV Gothic HS Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHS-Italic.ttf", title = "UDEV Gothic HS Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHS-BoldItalic.ttf", title = "UDEV Gothic HS BoldItalic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSJPDOC-Regular.ttf", title = "UDEV Gothic HSJPDOC Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSJPDOC-Bold.ttf", title = "UDEV Gothic HSJPDOC Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSJPDOC-Italic.ttf", title = "UDEV Gothic HSJPDOC Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSJPDOC-BoldItalic.ttf", title = "UDEV Gothic HSJPDOC BoldItalic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSLG-Regular.ttf", title = "UDEV Gothic HSLG Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSLG-Bold.ttf", title = "UDEV Gothic HSLG Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSLG-Italic.ttf", title = "UDEV Gothic HSLG Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothicHSLG-BoldItalic.ttf", title = "UDEV Gothic HSLG BoldItalic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HS-Regular.ttf", title = "UDEV Gothic 35HS Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HS-Bold.ttf", title = "UDEV Gothic 35HS Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HS-Italic.ttf", title = "UDEV Gothic 35HS Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HS-BoldItalic.ttf", title = "UDEV Gothic 35HS BoldItalic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSJPDOC-Regular.ttf", title = "UDEV Gothic 35HSJPDOC Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSJPDOC-Bold.ttf", title = "UDEV Gothic 35HSJPDOC Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSJPDOC-Italic.ttf", title = "UDEV Gothic 35HSJPDOC Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSJPDOC-BoldItalic.ttf", title = "UDEV Gothic 35HSJPDOC BoldItalic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSLG-Regular.ttf", title = "UDEV Gothic 35HSLG Regular" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSLG-Bold.ttf", title = "UDEV Gothic 35HSLG Bold" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSLG-Italic.ttf", title = "UDEV Gothic 35HSLG Italic" },
  { path = "UDEVGothic_HS_v2.1.0/UDEVGothic35HSLG-BoldItalic.ttf", title = "UDEV Gothic 35HSLG BoldItalic" },
]
