name = "noto-serif-cjk"
display-name = "Noto Serif CJK"
version = "2.003"
description = "Pan-CJK serif typeface for Chinese, Japanese, and Korean text"
aliases = []
homepage = "https://fonts.google.com/noto/use"
repository = "https://github.com/notofonts/noto-cjk"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/googlefonts/noto-cjk/raw/Serif2.003/Serif/Variable/OTC/NotoSerifCJK-VF.ttf.ttc"
hash = "sha256:e0be8fdd4f01c9807ee856ee0d30147f663c5ab397c491c80134266f58d1fffe"

[sources.contents]
type = "font-file"
title = "Noto Serif CJK"
