[package]
name = "yuru7/hackgen-nf"
version = "2.10.0"
description = "Hack と源柔ゴシックを合成したプログラミングフォント 白源 (はくげん／HackGen)"
homepage = "https://github.com/yuru7/HackGen"
repository = "https://github.com/yuru7/HackGen"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/HackGen/releases/download/v2.10.0/HackGen_NF_v2.10.0.zip"
hash = "sha256:f8abd483d5edfad88a78ed511978f43c83b43c48e364aa29ebe4a68217474428"
include = ["*/*.ttf"]
