name = "udev-gothic"
display-name = "UDEV Gothic"
version = "2.1.0"
description = "Japanese programming font combining BIZ UD Gothic and JetBrains Mono"
aliases = [
  "UDEV Gothic JPDOC",
  "UDEV Gothic LG",
  "UDEV Gothis 35",
  "UDEV Gothis 35JPDOC",
  "UDEV Gothis 35LG",
]
faces = [
  "UDEV Gothic Regular",
  "UDEV Gothic Bold",
  "UDEV Gothic Italic",
  "UDEV Gothic BoldItalic",
  "UDEV Gothic JPDOC Regular",
  "UDEV Gothic JPDOC Bold",
  "UDEV Gothic JPDOC Italic",
  "UDEV Gothic JPDOC BoldItalic",
  "UDEV Gothic LG Regular",
  "UDEV Gothic LG Bold",
  "UDEV Gothic LG Italic",
  "UDEV Gothic LG BoldItalic",
  "UDEV Gothic 35 Regular",
  "UDEV Gothic 35 Bold",
  "UDEV Gothic 35 Italic",
  "UDEV Gothic 35 BoldItalic",
  "UDEV Gothic 35JPDOC Regular",
  "UDEV Gothic 35JPDOC Bold",
  "UDEV Gothic 35JPDOC Italic",
  "UDEV Gothic 35JPDOC BoldItalic",
  "UDEV Gothic 35LG Regular",
  "UDEV Gothic 35LG Bold",
  "UDEV Gothic 35LG Italic",
  "UDEV Gothic 35LG BoldItalic",
]
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.1.0/UDEVGothic_v2.1.0.zip"
hash = "sha256:69c9321d3bac85589ddfee730e9582e3a9ca664d84d520fa7a70f656f1a0b8e5"
include = [
  "UDEVGothic_v2.1.0/UDEVGothic-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic-BoldItalic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35-BoldItalic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-BoldItalic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35LG-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35LG-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35LG-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothic35LG-BoldItalic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicJPDOC-BoldItalic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicLG-Regular.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicLG-Bold.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicLG-Italic.ttf",
  "UDEVGothic_v2.1.0/UDEVGothicLG-BoldItalic.ttf",
]
