name = "udev-gothic"
display-name = "UDEV Gothic"
version = "2.1.0"
description = "Japanese programming font combining BIZ UD Gothic and JetBrains Mono"
aliases = [
  "UDEV Gothic JPDOC",
  "UDEV Gothic LG",
  "UDEV Gothis 35",
  "UDEV Gothis 35JPDOC",
  "UDEV Gothis 35LG",
]
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.1.0/UDEVGothic_v2.1.0.zip"
hash = "sha256:69c9321d3bac85589ddfee730e9582e3a9ca664d84d520fa7a70f656f1a0b8e5"
files = [
  { path = "UDEVGothic_v2.1.0/UDEVGothic-Regular.ttf", title = "UDEV Gothic Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic-Bold.ttf", title = "UDEV Gothic Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic-Italic.ttf", title = "UDEV Gothic Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic-BoldItalic.ttf", title = "UDEV Gothic BoldItalic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Regular.ttf", title = "UDEV Gothic JPDOC Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Bold.ttf", title = "UDEV Gothic JPDOC Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicJPDOC-Italic.ttf", title = "UDEV Gothic JPDOC Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicJPDOC-BoldItalic.ttf", title = "UDEV Gothic JPDOC BoldItalic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicLG-Regular.ttf", title = "UDEV Gothic LG Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicLG-Bold.ttf", title = "UDEV Gothic LG Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicLG-Italic.ttf", title = "UDEV Gothic LG Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothicLG-BoldItalic.ttf", title = "UDEV Gothic LG BoldItalic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35-Regular.ttf", title = "UDEV Gothic 35 Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35-Bold.ttf", title = "UDEV Gothic 35 Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35-Italic.ttf", title = "UDEV Gothic 35 Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35-BoldItalic.ttf", title = "UDEV Gothic 35 BoldItalic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Regular.ttf", title = "UDEV Gothic 35JPDOC Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Bold.ttf", title = "UDEV Gothic 35JPDOC Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-Italic.ttf", title = "UDEV Gothic 35JPDOC Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35JPDOC-BoldItalic.ttf", title = "UDEV Gothic 35JPDOC BoldItalic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35LG-Regular.ttf", title = "UDEV Gothic 35LG Regular" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35LG-Bold.ttf", title = "UDEV Gothic 35LG Bold" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35LG-Italic.ttf", title = "UDEV Gothic 35LG Italic" },
  { path = "UDEVGothic_v2.1.0/UDEVGothic35LG-BoldItalic.ttf", title = "UDEV Gothic 35LG BoldItalic" },
]
