name = "biz-ud-gothic"
display-name = "BIZ UDGothic"
version = "1.051"
description = "Japanese universal design typeface designed to be easy to read and ideal for education and business documentation"
aliases = [
  "BIZ UDPGothic",
  "BIZ UDゴシック",
  "BIZ UDPゴシック",
]
faces = [
  "BIZ UDゴシック",
  "BIZ UDゴシック Bold",
  "BIZ UDPゴシック",
  "BIZ UDPゴシック Bold",
]
repository = "https://github.com/googlefonts/morisawa-biz-ud-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/googlefonts/morisawa-biz-ud-gothic/releases/download/v1.051/BIZUDGothic.zip"
hash = "sha256:30692df621b92df13b88f1360aed1ab6ae50de441bce751a396c6439045cd759"
include = [
  "BIZUDGothic-Bold.ttf",
  "BIZUDGothic-Regular.ttf",
  "BIZUDPGothic-Bold.ttf",
  "BIZUDPGothic-Regular.ttf",
]
