name = "firge"
version = "0.3.0"
description = "Japanese programming font combining Fira Mono and Genshin Gothic"
repository = "https://github.com/yuru7/Firge"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/Firge_v0.3.0.zip"
hash = "sha256:c986f621000a6598064c7e2078322ed02040af4f7804d258033df949b35b0527"

[sources.contents]
type = "archive"
fonts = [
  "Firge_v0.3.0/Firge-Regular.ttf",
  "Firge_v0.3.0/Firge-Bold.ttf",
  "Firge_v0.3.0/FirgeConsole-Regular.ttf",
  "Firge_v0.3.0/FirgeConsole-Bold.ttf",
  "Firge_v0.3.0/Firge35-Regular.ttf",
  "Firge_v0.3.0/Firge35-Bold.ttf",
  "Firge_v0.3.0/Firge35Console-Regular.ttf",
  "Firge_v0.3.0/Firge35Console-Bold.ttf",
]
