name = "firge-nerd"
display-name = "FirgeNerd Console"
version = "0.3.0"
description = "Japanese programming font combining Fira Mono and Genshin Gothic with Nerd Fonts"
aliases = [
  "Firge35Nerd Console",
]
repository = "https://github.com/yuru7/Firge"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/Firge/releases/download/v0.3.0/FirgeNerd_v0.3.0.zip"
hash = "sha256:54cd76378fbc5025f42d441d95ca6ec1d3ecc4270e6107558840fed7c04cfe4f"

[sources.contents]
type = "archive"
fonts = [
  { path = "FirgeNerd_v0.3.0/FirgeNerdConsole-Regular.ttf", title = "FirgeNerd Console Regular" },
  { path = "FirgeNerd_v0.3.0/FirgeNerdConsole-Bold.ttf", title = "FirgeNerd Console Bold" },
  { path = "FirgeNerd_v0.3.0/Firge35NerdConsole-Regular.ttf", title = "Firge35Nerd Console Regular" },
  { path = "FirgeNerd_v0.3.0/Firge35NerdConsole-Bold.ttf", title = "Firge35Nerd Console Bold" },
]
