name = "jetbrains-mono"
display-name = "JetBrains Mono"
version = "2.304"
description = "The free and open-source typeface for developers, by JetBrains"
aliases = [
  "JetBrains Mono NL",
]
homepage = "https://jetbrains.com/mono"
repository = "https://github.com/JetBrains/JetBrainsMono"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip"
hash = "sha256:6f6376c6ed2960ea8a963cd7387ec9d76e3f629125bc33d1fdcd7eb7012f7bbf"
files = [
  { path = "fonts/ttf/JetBrainsMono-Thin.ttf", title = "JetBrains Mono Thin" },
  { path = "fonts/ttf/JetBrainsMono-ExtraLight.ttf", title = "JetBrains Mono ExtraLight" },
  { path = "fonts/ttf/JetBrainsMono-Light.ttf", title = "JetBrains Mono Light" },
  { path = "fonts/ttf/JetBrainsMono-Regular.ttf", title = "JetBrains Mono Regular" },
  { path = "fonts/ttf/JetBrainsMono-Medium.ttf", title = "JetBrains Mono Medium" },
  { path = "fonts/ttf/JetBrainsMono-SemiBold.ttf", title = "JetBrains Mono SemiBold" },
  { path = "fonts/ttf/JetBrainsMono-Bold.ttf", title = "JetBrains Mono Bold" },
  { path = "fonts/ttf/JetBrainsMono-ExtraBold.ttf", title = "JetBrains Mono ExtraBold" },

  { path = "fonts/ttf/JetBrainsMono-ThinItalic.ttf", title = "JetBrains Mono Thin Italic" },
  { path = "fonts/ttf/JetBrainsMono-ExtraLightItalic.ttf", title = "JetBrains Mono ExtraLight Italic" },
  { path = "fonts/ttf/JetBrainsMono-LightItalic.ttf", title = "JetBrains Mono Light Italic" },
  { path = "fonts/ttf/JetBrainsMono-Italic.ttf", title = "JetBrains Mono Italic" },
  { path = "fonts/ttf/JetBrainsMono-MediumItalic.ttf", title = "JetBrains Mono Medium Italic" },
  { path = "fonts/ttf/JetBrainsMono-SemiBoldItalic.ttf", title = "JetBrains Mono SemiBold Italic" },
  { path = "fonts/ttf/JetBrainsMono-BoldItalic.ttf", title = "JetBrains Mono Bold Italic" },
  { path = "fonts/ttf/JetBrainsMono-ExtraBoldItalic.ttf", title = "JetBrains Mono ExtraBold Italic" },

  { path = "fonts/ttf/JetBrainsMonoNL-Thin.ttf", title = "JetBrains Mono NL Thin" },
  { path = "fonts/ttf/JetBrainsMonoNL-ExtraLight.ttf", title = "JetBrains Mono NL ExtraLight" },
  { path = "fonts/ttf/JetBrainsMonoNL-Light.ttf", title = "JetBrains Mono NL Light" },
  { path = "fonts/ttf/JetBrainsMonoNL-Regular.ttf", title = "JetBrains Mono NL Regular" },
  { path = "fonts/ttf/JetBrainsMonoNL-Medium.ttf", title = "JetBrains Mono NL Medium" },
  { path = "fonts/ttf/JetBrainsMonoNL-SemiBold.ttf", title = "JetBrains Mono NL SemiBold" },
  { path = "fonts/ttf/JetBrainsMonoNL-Bold.ttf", title = "JetBrains Mono NL Bold" },
  { path = "fonts/ttf/JetBrainsMonoNL-ExtraBold.ttf", title = "JetBrains Mono NL ExtraBold" },

  { path = "fonts/ttf/JetBrainsMonoNL-ThinItalic.ttf", title = "JetBrains Mono NL Thin Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-ExtraLightItalic.ttf", title = "JetBrains Mono NL ExtraLight Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-LightItalic.ttf", title = "JetBrains Mono NL Light Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-Italic.ttf", title = "JetBrains Mono NL Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-MediumItalic.ttf", title = "JetBrains Mono NL Medium Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-SemiBoldItalic.ttf", title = "JetBrains Mono NL SemiBold Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-BoldItalic.ttf", title = "JetBrains Mono NL Bold Italic" },
  { path = "fonts/ttf/JetBrainsMonoNL-ExtraBoldItalic.ttf", title = "JetBrains Mono NL ExtraBold Italic" },
]
ignore = [
  "fonts/variable/JetBrainsMono[wght].ttf",
  "fonts/variable/JetBrainsMono-Italic[wght].ttf",
]
