name = "hackgen"
display-name = "HackGen"
version = "2.9.1"
description = "Japanese programming font combining Hack and GenJyuu Gothic"
aliases = ["HackGen Console", "HackGen35", "HackGen35 Console"]
repository = "https://github.com/yuru7/HackGen"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/HackGen/releases/download/v2.9.1/HackGen_v2.9.1.zip"
hash = "sha256:66f2f00fb7ae00f098fb1683d0a665373f5900f9aa1447b273d70e86a868ec77"
files = [
  { path = "HackGen_v2.9.1/HackGen-Regular.ttf", title = "HackGen Regular" },
  { path = "HackGen_v2.9.1/HackGen-Bold.ttf", title = "HackGen Bold" },
  { path = "HackGen_v2.9.1/HackGenConsole-Regular.ttf", title = "HackGen Console Regular" },
  { path = "HackGen_v2.9.1/HackGenConsole-Bold.ttf", title = "HackGen Console Bold" },
  { path = "HackGen_v2.9.1/HackGen35-Regular.ttf", title = "HackGen35 Regular" },
  { path = "HackGen_v2.9.1/HackGen35-Bold.ttf", title = "HackGen35 Bold" },
  { path = "HackGen_v2.9.1/HackGen35Console-Regular.ttf", title = "HackGen35 Console Regular" },
  { path = "HackGen_v2.9.1/HackGen35Console-Bold.ttf", title = "HackGen35 Console Bold" },
]
