name = "hackgen-nf"
display-name = "HackGen NF"
version = "2.10.0"
description = "Japanese programming font combining Hack and GenJyuu Gothic with Nerd Fonts"
aliases = [
  "HackGen Console NF",
  "HackGen35 Console NF",
]
repository = "https://github.com/yuru7/HackGen"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/HackGen/releases/download/v2.10.0/HackGen_NF_v2.10.0.zip"
hash = "sha256:f8abd483d5edfad88a78ed511978f43c83b43c48e364aa29ebe4a68217474428"
files = [
  { path = "HackGen_NF_v2.10.0/HackGenConsoleNF-Regular.ttf", title = "HackGen Console NF Regular" },
  { path = "HackGen_NF_v2.10.0/HackGenConsoleNF-Bold.ttf", title = "HackGen Console NF Bold" },
  { path = "HackGen_NF_v2.10.0/HackGen35ConsoleNF-Regular.ttf", title = "HackGen35 Console NF Regular" },
  { path = "HackGen_NF_v2.10.0/HackGen35ConsoleNF-Bold.ttf", title = "HackGen35 Console NF Bold" },
]
