[package]
name = "yuru7/udev-gothic-hs"
version = "2.2.0"
description = "UDEV Gothic は、ユニバーサルデザインフォントのBIZ UDゴシックと、 開発者向けフォントの JetBrains Mono を合成した、プログラミング向けフォントです。"
homepage = "https://github.com/yuru7/udev-gothic"
repository = "https://github.com/yuru7/udev-gothic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/yuru7/udev-gothic/releases/download/v2.2.0/UDEVGothic_HS_v2.2.0.zip"
hash = "sha256:570d03cb98d15834a5f6e1323843dfdc9f79d4b0c4bace123bb12de0806d9545"
include = ["*/*.ttf"]
