name = "noto-sans"
display-name = "Noto Sans"
version = "2.015"
description = "Sans-serif typeface for Latin, Greek, and Cyrillic text"
aliases = []
homepage = "https://fonts.google.com/noto/use"
repository = "https://github.com/notofonts/latin-greek-cyrillic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v2.015/NotoSans-v2.015.zip"
hash = "sha256:0c34df072a3fa7efbb7cbf34950e1f971a4447cffe365d3a359e2d4089b958f5"

[sources.contents]
type = "archive"
fonts = [
  { path = "NotoSans/hinted/ttf/NotoSans-Black.ttf", title = "Noto Sans Black" },
  { path = "NotoSans/hinted/ttf/NotoSans-BlackItalic.ttf", title = "Noto Sans Black Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Bold.ttf", title = "Noto Sans Bold" },
  { path = "NotoSans/hinted/ttf/NotoSans-BoldItalic.ttf", title = "Noto Sans Bold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Condensed.ttf", title = "Noto Sans Condensed" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedBlack.ttf", title = "Noto Sans Condensed Black" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedBlackItalic.ttf", title = "Noto Sans Condensed Black Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedBold.ttf", title = "Noto Sans Condensed Bold" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedBoldItalic.ttf", title = "Noto Sans Condensed Bold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedExtraBold.ttf", title = "Noto Sans Condensed ExtraBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedExtraBoldItalic.ttf", title = "Noto Sans Condensed ExtraBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedExtraLight.ttf", title = "Noto Sans Condensed ExtraLight" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedExtraLightItalic.ttf", title = "Noto Sans Condensed ExtraLight Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedItalic.ttf", title = "Noto Sans Condensed Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedLight.ttf", title = "Noto Sans Condensed Light" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedLightItalic.ttf", title = "Noto Sans Condensed Light Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedMedium.ttf", title = "Noto Sans Condensed Medium" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedMediumItalic.ttf", title = "Noto Sans Condensed Medium Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedSemiBold.ttf", title = "Noto Sans Condensed SemiBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedSemiBoldItalic.ttf", title = "Noto Sans Condensed SemiBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedThin.ttf", title = "Noto Sans Condensed Thin" },
  { path = "NotoSans/hinted/ttf/NotoSans-CondensedThinItalic.ttf", title = "Noto Sans Condensed Thin Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraBold.ttf", title = "Noto Sans ExtraBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraBoldItalic.ttf", title = "Noto Sans ExtraBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensed.ttf", title = "Noto Sans ExtraCondensed" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBlack.ttf", title = "Noto Sans ExtraCondensed Black" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBlackItalic.ttf", title = "Noto Sans ExtraCondensed Black Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBold.ttf", title = "Noto Sans ExtraCondensed Bold" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBoldItalic.ttf", title = "Noto Sans ExtraCondensed Bold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraBold.ttf", title = "Noto Sans ExtraCondensed ExtraBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraBoldItalic.ttf", title = "Noto Sans ExtraCondensed ExtraBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraLight.ttf", title = "Noto Sans ExtraCondensed ExtraLight" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraLightItalic.ttf", title = "Noto Sans ExtraCondensed ExtraLight Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedItalic.ttf", title = "Noto Sans ExtraCondensed Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedLight.ttf", title = "Noto Sans ExtraCondensed Light" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedLightItalic.ttf", title = "Noto Sans ExtraCondensed Light Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedMedium.ttf", title = "Noto Sans ExtraCondensed Medium" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedMediumItalic.ttf", title = "Noto Sans ExtraCondensed Medium Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedSemiBold.ttf", title = "Noto Sans ExtraCondensed SemiBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedSemiBoldItalic.ttf", title = "Noto Sans ExtraCondensed SemiBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedThin.ttf", title = "Noto Sans ExtraCondensed Thin" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraCondensedThinItalic.ttf", title = "Noto Sans ExtraCondensed Thin Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraLight.ttf", title = "Noto Sans ExtraLight" },
  { path = "NotoSans/hinted/ttf/NotoSans-ExtraLightItalic.ttf", title = "Noto Sans ExtraLight Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Italic.ttf", title = "Noto Sans Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Light.ttf", title = "Noto Sans Light" },
  { path = "NotoSans/hinted/ttf/NotoSans-LightItalic.ttf", title = "Noto Sans Light Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Medium.ttf", title = "Noto Sans Medium" },
  { path = "NotoSans/hinted/ttf/NotoSans-MediumItalic.ttf", title = "Noto Sans Medium Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Regular.ttf", title = "Noto Sans Regular" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiBold.ttf", title = "Noto Sans SemiBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiBoldItalic.ttf", title = "Noto Sans SemiBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensed.ttf", title = "Noto Sans SemiCondensed" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedBlack.ttf", title = "Noto Sans SemiCondensed Black" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedBlackItalic.ttf", title = "Noto Sans SemiCondensed Black Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedBold.ttf", title = "Noto Sans SemiCondensed Bold" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedBoldItalic.ttf", title = "Noto Sans SemiCondensed Bold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraBold.ttf", title = "Noto Sans SemiCondensed ExtraBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraBoldItalic.ttf", title = "Noto Sans SemiCondensed ExtraBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraLight.ttf", title = "Noto Sans SemiCondensed ExtraLight" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraLightItalic.ttf", title = "Noto Sans SemiCondensed ExtraLight Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedItalic.ttf", title = "Noto Sans SemiCondensed Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedLight.ttf", title = "Noto Sans SemiCondensed Light" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedLightItalic.ttf", title = "Noto Sans SemiCondensed Light Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedMedium.ttf", title = "Noto Sans SemiCondensed Medium" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedMediumItalic.ttf", title = "Noto Sans SemiCondensed Medium Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedSemiBold.ttf", title = "Noto Sans SemiCondensed SemiBold" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedSemiBoldItalic.ttf", title = "Noto Sans SemiCondensed SemiBold Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedThin.ttf", title = "Noto Sans SemiCondensed Thin" },
  { path = "NotoSans/hinted/ttf/NotoSans-SemiCondensedThinItalic.ttf", title = "Noto Sans SemiCondensed Thin Italic" },
  { path = "NotoSans/hinted/ttf/NotoSans-Thin.ttf", title = "Noto Sans Thin" },
  { path = "NotoSans/hinted/ttf/NotoSans-ThinItalic.ttf", title = "Noto Sans Thin Italic" },
]
ignore = [
  { glob = "NotoSans/full/otf/*.otf" },
  { glob = "NotoSans/full/slim-variable-ttf/*.ttf" },
  { glob = "NotoSans/full/ttf/*.ttf" },
  { glob = "NotoSans/full/variable-ttf/*.ttf" },
  { glob = "NotoSans/googlefonts/variable-ttf/*.ttf" },
  { glob = "NotoSans/unhinted/otf/*.otf" },
  { glob = "NotoSans/unhinted/slim-variable-ttf/*.ttf" },
  { glob = "NotoSans/unhinted/ttf/*.ttf" },
  { glob = "NotoSans/unhinted/variable-ttf/*.ttf" },
]
