name = "noto-sans"
version = "2.015"
description = "Sans-serif typeface for Latin, Greek, and Cyrillic text"
homepage = "https://fonts.google.com/noto/use"
repository = "https://github.com/notofonts/latin-greek-cyrillic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v2.015/NotoSans-v2.015.zip"
hash = "sha256:0c34df072a3fa7efbb7cbf34950e1f971a4447cffe365d3a359e2d4089b958f5"

[sources.contents]
type = "archive"
fonts = [
  "NotoSans/hinted/ttf/NotoSans-Black.ttf",
  "NotoSans/hinted/ttf/NotoSans-BlackItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Bold.ttf",
  "NotoSans/hinted/ttf/NotoSans-BoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Condensed.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedBlack.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedBlackItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedExtraBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedExtraBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedExtraLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedExtraLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedMedium.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedMediumItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedSemiBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedSemiBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedThin.ttf",
  "NotoSans/hinted/ttf/NotoSans-CondensedThinItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensed.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBlack.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBlackItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedExtraLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedMedium.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedMediumItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedSemiBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedSemiBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedThin.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraCondensedThinItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-ExtraLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Italic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Light.ttf",
  "NotoSans/hinted/ttf/NotoSans-LightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Medium.ttf",
  "NotoSans/hinted/ttf/NotoSans-MediumItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Regular.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensed.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedBlack.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedBlackItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedExtraLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedLight.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedLightItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedMedium.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedMediumItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedSemiBold.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedSemiBoldItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedThin.ttf",
  "NotoSans/hinted/ttf/NotoSans-SemiCondensedThinItalic.ttf",
  "NotoSans/hinted/ttf/NotoSans-Thin.ttf",
  "NotoSans/hinted/ttf/NotoSans-ThinItalic.ttf",
]
ignore = [
  { glob = "NotoSans/full/otf/*.otf" },
  { glob = "NotoSans/full/slim-variable-ttf/*.ttf" },
  { glob = "NotoSans/full/ttf/*.ttf" },
  { glob = "NotoSans/full/variable-ttf/*.ttf" },
  { glob = "NotoSans/googlefonts/variable-ttf/*.ttf" },
  { glob = "NotoSans/unhinted/otf/*.otf" },
  { glob = "NotoSans/unhinted/slim-variable-ttf/*.ttf" },
  { glob = "NotoSans/unhinted/ttf/*.ttf" },
  { glob = "NotoSans/unhinted/variable-ttf/*.ttf" },
]
