name = "noto-serif"
display-name = "Noto Serif"
version = "2.015"
description = "Serif typeface for Latin, Greek, and Cyrillic text"
aliases = []
homepage = "https://fonts.google.com/noto/use"
repository = "https://github.com/notofonts/latin-greek-cyrillic"
license = "OFL-1.1"

[[sources]]
url = "https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSerif-v2.015/NotoSerif-v2.015.zip"
hash = "sha256:0e9a43c8a4b94ac76f55069ed1d7385bbcaf6b99527a94deb5619e032b7e76c1"

[sources.contents]
type = "archive"
fonts = [
  "NotoSerif/hinted/ttf/NotoSerif-Black.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-BlackItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Bold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-BoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Condensed.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedBlack.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedBlackItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedExtraBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedExtraBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedExtraLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedExtraLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedMedium.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedMediumItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedSemiBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedSemiBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedThin.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-CondensedThinItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensed.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedBlack.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedBlackItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedExtraBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedExtraBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedExtraLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedExtraLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedMedium.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedMediumItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedSemiBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedSemiBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedThin.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraCondensedThinItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ExtraLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Italic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Light.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-LightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Medium.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-MediumItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Regular.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensed.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedBlack.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedBlackItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedExtraBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedExtraBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedExtraLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedExtraLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedLight.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedLightItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedMedium.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedMediumItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedSemiBold.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedSemiBoldItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedThin.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-SemiCondensedThinItalic.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-Thin.ttf",
  "NotoSerif/hinted/ttf/NotoSerif-ThinItalic.ttf",
]
ignore = [
  { glob = "NotoSerif/googlefonts/variable-ttf/*.ttf" },
  { glob = "NotoSerif/unhinted/otf/*.otf" },
  { glob = "NotoSerif/unhinted/slim-variable-ttf/*.ttf" },
  { glob = "NotoSerif/unhinted/ttf/*.ttf" },
  { glob = "NotoSerif/unhinted/variable-ttf/*.ttf" },
]
